#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 17
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 5
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_LBRACK = 1,
  anon_sym_RBRACK = 2,
  anon_sym_LBRACE = 3,
  anon_sym_RBRACE = 4,
  anon_sym_LT_LT = 5,
  anon_sym_GT_GT = 6,
  sym_operator = 7,
  sym_literal = 8,
  anon_sym_LPAREN = 9,
  anon_sym_RPAREN = 10,
  anon_sym_LT = 11,
  anon_sym_GT = 12,
  anon_sym_LT_TILDE = 13,
  anon_sym_TILDE_GT = 14,
  aux_sym_escape_sequence_token1 = 15,
  aux_sym_escape_sequence_token2 = 16,
  sym_real_number = 17,
  sym_integer = 18,
  sym_comment = 19,
  sym_structure_comment = 20,
  sym_literal_string = 21,
  sym_hexadecimal_string = 22,
  sym_base85_string = 23,
  sym_radix_number = 24,
  sym_document = 25,
  sym__element = 26,
  sym_array = 27,
  sym_procedure = 28,
  sym_dictionary = 29,
  sym_string = 30,
  sym_escape_sequence = 31,
  aux_sym_document_repeat1 = 32,
  aux_sym_array_repeat1 = 33,
  aux_sym_string_repeat1 = 34,
  aux_sym_string_repeat2 = 35,
  aux_sym_string_repeat3 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LT_LT] = "<<",
  [anon_sym_GT_GT] = ">>",
  [sym_operator] = "operator",
  [sym_literal] = "literal",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_TILDE] = "<~",
  [anon_sym_TILDE_GT] = "~>",
  [aux_sym_escape_sequence_token1] = "escape_sequence_token1",
  [aux_sym_escape_sequence_token2] = "escape_sequence_token2",
  [sym_real_number] = "real_number",
  [sym_integer] = "integer",
  [sym_comment] = "comment",
  [sym_structure_comment] = "structure_comment",
  [sym_literal_string] = "literal_string",
  [sym_hexadecimal_string] = "hexadecimal_string",
  [sym_base85_string] = "base85_string",
  [sym_radix_number] = "radix_number",
  [sym_document] = "document",
  [sym__element] = "_element",
  [sym_array] = "array",
  [sym_procedure] = "procedure",
  [sym_dictionary] = "dictionary",
  [sym_string] = "string",
  [sym_escape_sequence] = "escape_sequence",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_array_repeat1] = "array_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym_string_repeat3] = "string_repeat3",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LT_LT] = anon_sym_LT_LT,
  [anon_sym_GT_GT] = anon_sym_GT_GT,
  [sym_operator] = sym_operator,
  [sym_literal] = sym_literal,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_TILDE] = anon_sym_LT_TILDE,
  [anon_sym_TILDE_GT] = anon_sym_TILDE_GT,
  [aux_sym_escape_sequence_token1] = aux_sym_escape_sequence_token1,
  [aux_sym_escape_sequence_token2] = aux_sym_escape_sequence_token2,
  [sym_real_number] = sym_real_number,
  [sym_integer] = sym_integer,
  [sym_comment] = sym_comment,
  [sym_structure_comment] = sym_structure_comment,
  [sym_literal_string] = sym_literal_string,
  [sym_hexadecimal_string] = sym_hexadecimal_string,
  [sym_base85_string] = sym_base85_string,
  [sym_radix_number] = sym_radix_number,
  [sym_document] = sym_document,
  [sym__element] = sym__element,
  [sym_array] = sym_array,
  [sym_procedure] = sym_procedure,
  [sym_dictionary] = sym_dictionary,
  [sym_string] = sym_string,
  [sym_escape_sequence] = sym_escape_sequence,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_array_repeat1] = aux_sym_array_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym_string_repeat3] = aux_sym_string_repeat3,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_escape_sequence_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_escape_sequence_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_real_number] = {
    .visible = true,
    .named = true,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_structure_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_hexadecimal_string] = {
    .visible = true,
    .named = true,
  },
  [sym_base85_string] = {
    .visible = true,
    .named = true,
  },
  [sym_radix_number] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__element] = {
    .visible = false,
    .named = true,
  },
  [sym_array] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure] = {
    .visible = true,
    .named = true,
  },
  [sym_dictionary] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_array_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat3] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 9,
  [12] = 7,
  [13] = 10,
  [14] = 5,
  [15] = 6,
  [16] = 8,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 18,
  [26] = 20,
  [27] = 21,
  [28] = 24,
  [29] = 22,
  [30] = 19,
  [31] = 23,
  [32] = 17,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
  [37] = 34,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 40,
  [45] = 45,
  [46] = 45,
  [47] = 42,
  [48] = 43,
  [49] = 49,
};

static TSCharacterRange sym_operator_character_set_1[] = {
  {'!', '$'}, {'&', '\''}, {'*', '.'}, {'0', ';'}, {'=', '='}, {'?', 'Z'}, {'^', 'z'}, {'|', '|'},
  {'~', '~'},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      ADVANCE_MAP(
        '%', 34,
        '(', 21,
        ')', 22,
        '.', 17,
        '/', 3,
        '<', 23,
        '>', 24,
        '[', 9,
        '\\', 6,
        ']', 10,
        '{', 11,
        '}', 12,
        '+', 15,
        '-', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('!' <= lookahead && lookahead <= '~')) ADVANCE(19);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '%', 34,
        '(', 21,
        '.', 17,
        '/', 3,
        '<', 23,
        '>', 4,
        '[', 9,
        ']', 10,
        '{', 11,
        '}', 12,
        '+', 15,
        '-', 15,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (('!' <= lookahead && lookahead <= '\'') ||
          ('*' <= lookahead && lookahead <= 'Z') ||
          ('^' <= lookahead && lookahead <= '~')) ADVANCE(19);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(34);
      if (lookahead == '~') ADVANCE(5);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '/') ADVANCE(7);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(14);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(26);
      END_STATE();
    case 6:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(29);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 7:
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_LT_LT);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_GT_GT);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '.') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_operator);
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(18);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(19);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(19);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_operator);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_operator);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_literal);
      if (set_contains(sym_operator_character_set_1, 9, lookahead)) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '<') ADVANCE(13);
      if (lookahead == '~') ADVANCE(25);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LT_TILDE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_TILDE_GT);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(27);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(28);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_escape_sequence_token2);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_real_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_real_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(34);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 1, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 2},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 3},
  [8] = {.lex_state = 0, .external_lex_state = 3},
  [9] = {.lex_state = 1, .external_lex_state = 3},
  [10] = {.lex_state = 1, .external_lex_state = 3},
  [11] = {.lex_state = 1, .external_lex_state = 3},
  [12] = {.lex_state = 0, .external_lex_state = 3},
  [13] = {.lex_state = 1, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 3},
  [15] = {.lex_state = 0, .external_lex_state = 3},
  [16] = {.lex_state = 0, .external_lex_state = 3},
  [17] = {.lex_state = 1, .external_lex_state = 3},
  [18] = {.lex_state = 1, .external_lex_state = 3},
  [19] = {.lex_state = 1, .external_lex_state = 3},
  [20] = {.lex_state = 1, .external_lex_state = 3},
  [21] = {.lex_state = 1, .external_lex_state = 3},
  [22] = {.lex_state = 1, .external_lex_state = 3},
  [23] = {.lex_state = 1, .external_lex_state = 3},
  [24] = {.lex_state = 1, .external_lex_state = 3},
  [25] = {.lex_state = 0, .external_lex_state = 2},
  [26] = {.lex_state = 0, .external_lex_state = 2},
  [27] = {.lex_state = 0, .external_lex_state = 2},
  [28] = {.lex_state = 0, .external_lex_state = 2},
  [29] = {.lex_state = 0, .external_lex_state = 2},
  [30] = {.lex_state = 0, .external_lex_state = 2},
  [31] = {.lex_state = 0, .external_lex_state = 2},
  [32] = {.lex_state = 0, .external_lex_state = 2},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 4},
  [37] = {.lex_state = 0, .external_lex_state = 4},
  [38] = {.lex_state = 0, .external_lex_state = 4},
  [39] = {.lex_state = 0, .external_lex_state = 5},
  [40] = {.lex_state = 2, .external_lex_state = 6},
  [41] = {.lex_state = 2, .external_lex_state = 6},
  [42] = {.lex_state = 0, .external_lex_state = 5},
  [43] = {.lex_state = 2, .external_lex_state = 6},
  [44] = {.lex_state = 2, .external_lex_state = 6},
  [45] = {.lex_state = 0, .external_lex_state = 5},
  [46] = {.lex_state = 0, .external_lex_state = 5},
  [47] = {.lex_state = 0, .external_lex_state = 5},
  [48] = {.lex_state = 2, .external_lex_state = 6},
  [49] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT_LT] = ACTIONS(1),
    [sym_operator] = ACTIONS(1),
    [sym_literal] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_TILDE] = ACTIONS(1),
    [aux_sym_escape_sequence_token1] = ACTIONS(1),
    [aux_sym_escape_sequence_token2] = ACTIONS(1),
    [sym_real_number] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym_structure_comment] = ACTIONS(1),
    [sym_literal_string] = ACTIONS(1),
    [sym_hexadecimal_string] = ACTIONS(1),
    [sym_base85_string] = ACTIONS(1),
    [sym_radix_number] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(49),
    [sym__element] = STATE(4),
    [sym_array] = STATE(4),
    [sym_procedure] = STATE(4),
    [sym_dictionary] = STATE(4),
    [sym_string] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LT_LT] = ACTIONS(11),
    [sym_operator] = ACTIONS(13),
    [sym_literal] = ACTIONS(15),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_TILDE] = ACTIONS(21),
    [sym_real_number] = ACTIONS(13),
    [sym_integer] = ACTIONS(15),
    [sym_comment] = ACTIONS(3),
    [sym_structure_comment] = ACTIONS(15),
    [sym_radix_number] = ACTIONS(15),
  },
  [2] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(23),
    [anon_sym_RBRACK] = ACTIONS(26),
    [anon_sym_LBRACE] = ACTIONS(28),
    [anon_sym_RBRACE] = ACTIONS(26),
    [anon_sym_LT_LT] = ACTIONS(31),
    [anon_sym_GT_GT] = ACTIONS(26),
    [sym_operator] = ACTIONS(34),
    [sym_literal] = ACTIONS(37),
    [anon_sym_LPAREN] = ACTIONS(40),
    [anon_sym_LT] = ACTIONS(43),
    [anon_sym_LT_TILDE] = ACTIONS(46),
    [sym_real_number] = ACTIONS(34),
    [sym_integer] = ACTIONS(37),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(37),
  },
  [3] = {
    [sym__element] = STATE(3),
    [sym_array] = STATE(3),
    [sym_procedure] = STATE(3),
    [sym_dictionary] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_LBRACK] = ACTIONS(51),
    [anon_sym_LBRACE] = ACTIONS(54),
    [anon_sym_LT_LT] = ACTIONS(57),
    [sym_operator] = ACTIONS(60),
    [sym_literal] = ACTIONS(63),
    [anon_sym_LPAREN] = ACTIONS(66),
    [anon_sym_LT] = ACTIONS(69),
    [anon_sym_LT_TILDE] = ACTIONS(72),
    [sym_real_number] = ACTIONS(60),
    [sym_integer] = ACTIONS(63),
    [sym_comment] = ACTIONS(3),
    [sym_structure_comment] = ACTIONS(63),
    [sym_radix_number] = ACTIONS(63),
  },
  [4] = {
    [sym__element] = STATE(3),
    [sym_array] = STATE(3),
    [sym_procedure] = STATE(3),
    [sym_dictionary] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_document_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(75),
    [anon_sym_LBRACK] = ACTIONS(7),
    [anon_sym_LBRACE] = ACTIONS(9),
    [anon_sym_LT_LT] = ACTIONS(11),
    [sym_operator] = ACTIONS(77),
    [sym_literal] = ACTIONS(79),
    [anon_sym_LPAREN] = ACTIONS(17),
    [anon_sym_LT] = ACTIONS(19),
    [anon_sym_LT_TILDE] = ACTIONS(21),
    [sym_real_number] = ACTIONS(77),
    [sym_integer] = ACTIONS(79),
    [sym_comment] = ACTIONS(3),
    [sym_structure_comment] = ACTIONS(79),
    [sym_radix_number] = ACTIONS(79),
  },
  [5] = {
    [sym__element] = STATE(7),
    [sym_array] = STATE(7),
    [sym_procedure] = STATE(7),
    [sym_dictionary] = STATE(7),
    [sym_string] = STATE(7),
    [aux_sym_array_repeat1] = STATE(7),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(83),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(89),
    [sym_literal] = ACTIONS(91),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(89),
    [sym_integer] = ACTIONS(91),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(91),
  },
  [6] = {
    [sym__element] = STATE(8),
    [sym_array] = STATE(8),
    [sym_procedure] = STATE(8),
    [sym_dictionary] = STATE(8),
    [sym_string] = STATE(8),
    [aux_sym_array_repeat1] = STATE(8),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(99),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(101),
    [sym_literal] = ACTIONS(103),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(101),
    [sym_integer] = ACTIONS(103),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(103),
  },
  [7] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(105),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(107),
    [sym_literal] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(107),
    [sym_integer] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(109),
  },
  [8] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(111),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(107),
    [sym_literal] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(107),
    [sym_integer] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(109),
  },
  [9] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [anon_sym_GT_GT] = ACTIONS(113),
    [sym_operator] = ACTIONS(107),
    [sym_literal] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(107),
    [sym_integer] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(109),
  },
  [10] = {
    [sym__element] = STATE(9),
    [sym_array] = STATE(9),
    [sym_procedure] = STATE(9),
    [sym_dictionary] = STATE(9),
    [sym_string] = STATE(9),
    [aux_sym_array_repeat1] = STATE(9),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [anon_sym_GT_GT] = ACTIONS(115),
    [sym_operator] = ACTIONS(117),
    [sym_literal] = ACTIONS(119),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(117),
    [sym_integer] = ACTIONS(119),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(119),
  },
  [11] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [anon_sym_GT_GT] = ACTIONS(121),
    [sym_operator] = ACTIONS(107),
    [sym_literal] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(107),
    [sym_integer] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(109),
  },
  [12] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(123),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(107),
    [sym_literal] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(107),
    [sym_integer] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(109),
  },
  [13] = {
    [sym__element] = STATE(11),
    [sym_array] = STATE(11),
    [sym_procedure] = STATE(11),
    [sym_dictionary] = STATE(11),
    [sym_string] = STATE(11),
    [aux_sym_array_repeat1] = STATE(11),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [anon_sym_GT_GT] = ACTIONS(125),
    [sym_operator] = ACTIONS(127),
    [sym_literal] = ACTIONS(129),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(127),
    [sym_integer] = ACTIONS(129),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(129),
  },
  [14] = {
    [sym__element] = STATE(12),
    [sym_array] = STATE(12),
    [sym_procedure] = STATE(12),
    [sym_dictionary] = STATE(12),
    [sym_string] = STATE(12),
    [aux_sym_array_repeat1] = STATE(12),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_RBRACK] = ACTIONS(131),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(133),
    [sym_literal] = ACTIONS(135),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(133),
    [sym_integer] = ACTIONS(135),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(135),
  },
  [15] = {
    [sym__element] = STATE(16),
    [sym_array] = STATE(16),
    [sym_procedure] = STATE(16),
    [sym_dictionary] = STATE(16),
    [sym_string] = STATE(16),
    [aux_sym_array_repeat1] = STATE(16),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(137),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(139),
    [sym_literal] = ACTIONS(141),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(139),
    [sym_integer] = ACTIONS(141),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(141),
  },
  [16] = {
    [sym__element] = STATE(2),
    [sym_array] = STATE(2),
    [sym_procedure] = STATE(2),
    [sym_dictionary] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_array_repeat1] = STATE(2),
    [anon_sym_LBRACK] = ACTIONS(81),
    [anon_sym_LBRACE] = ACTIONS(85),
    [anon_sym_RBRACE] = ACTIONS(143),
    [anon_sym_LT_LT] = ACTIONS(87),
    [sym_operator] = ACTIONS(107),
    [sym_literal] = ACTIONS(109),
    [anon_sym_LPAREN] = ACTIONS(93),
    [anon_sym_LT] = ACTIONS(95),
    [anon_sym_LT_TILDE] = ACTIONS(97),
    [sym_real_number] = ACTIONS(107),
    [sym_integer] = ACTIONS(109),
    [sym_comment] = ACTIONS(3),
    [sym_radix_number] = ACTIONS(109),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(145), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [22] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(149), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [44] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(153), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [66] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(157), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [88] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(161), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [110] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(165), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [132] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(169), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [154] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(173), 11,
      sym_radix_number,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_LT_LT,
      anon_sym_GT_GT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [176] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(151), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(149), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [197] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(159), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(157), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [218] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(163), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(161), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [239] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(175), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(173), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(167), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(165), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [281] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(155), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(153), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [302] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(171), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(169), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [323] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(147), 3,
      sym_operator,
      anon_sym_LT,
      sym_real_number,
    ACTIONS(145), 10,
      sym_structure_comment,
      sym_radix_number,
      ts_builtin_sym_end,
      anon_sym_LBRACK,
      anon_sym_LBRACE,
      anon_sym_LT_LT,
      sym_literal,
      anon_sym_LPAREN,
      anon_sym_LT_TILDE,
      sym_integer,
  [344] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 1,
      anon_sym_RPAREN,
    ACTIONS(182), 1,
      sym_literal_string,
    ACTIONS(179), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(33), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [362] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_RPAREN,
    ACTIONS(189), 1,
      sym_literal_string,
    ACTIONS(187), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(33), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [380] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_RPAREN,
    ACTIONS(193), 1,
      sym_literal_string,
    ACTIONS(187), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(37), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [398] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_RPAREN,
    ACTIONS(197), 1,
      sym_literal_string,
    ACTIONS(187), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(34), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [416] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 1,
      sym_literal_string,
    ACTIONS(199), 1,
      anon_sym_RPAREN,
    ACTIONS(187), 2,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
    STATE(33), 2,
      sym_escape_sequence,
      aux_sym_string_repeat1,
  [434] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(201), 4,
      sym_literal_string,
      anon_sym_RPAREN,
      aux_sym_escape_sequence_token1,
      aux_sym_escape_sequence_token2,
  [444] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(203), 1,
      anon_sym_GT,
    ACTIONS(205), 1,
      sym_hexadecimal_string,
    STATE(39), 1,
      aux_sym_string_repeat2,
  [457] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_TILDE_GT,
    ACTIONS(208), 1,
      sym_base85_string,
    STATE(43), 1,
      aux_sym_string_repeat3,
  [470] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(210), 1,
      anon_sym_TILDE_GT,
    ACTIONS(212), 1,
      sym_base85_string,
    STATE(41), 1,
      aux_sym_string_repeat3,
  [483] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_GT,
    ACTIONS(215), 1,
      sym_hexadecimal_string,
    STATE(39), 1,
      aux_sym_string_repeat2,
  [496] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 1,
      anon_sym_TILDE_GT,
    ACTIONS(217), 1,
      sym_base85_string,
    STATE(41), 1,
      aux_sym_string_repeat3,
  [509] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_TILDE_GT,
    ACTIONS(219), 1,
      sym_base85_string,
    STATE(48), 1,
      aux_sym_string_repeat3,
  [522] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(195), 1,
      anon_sym_GT,
    ACTIONS(221), 1,
      sym_hexadecimal_string,
    STATE(42), 1,
      aux_sym_string_repeat2,
  [535] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_GT,
    ACTIONS(223), 1,
      sym_hexadecimal_string,
    STATE(47), 1,
      aux_sym_string_repeat2,
  [548] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_GT,
    ACTIONS(215), 1,
      sym_hexadecimal_string,
    STATE(39), 1,
      aux_sym_string_repeat2,
  [561] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(199), 1,
      anon_sym_TILDE_GT,
    ACTIONS(217), 1,
      sym_base85_string,
    STATE(41), 1,
      aux_sym_string_repeat3,
  [574] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(225), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(17)] = 0,
  [SMALL_STATE(18)] = 22,
  [SMALL_STATE(19)] = 44,
  [SMALL_STATE(20)] = 66,
  [SMALL_STATE(21)] = 88,
  [SMALL_STATE(22)] = 110,
  [SMALL_STATE(23)] = 132,
  [SMALL_STATE(24)] = 154,
  [SMALL_STATE(25)] = 176,
  [SMALL_STATE(26)] = 197,
  [SMALL_STATE(27)] = 218,
  [SMALL_STATE(28)] = 239,
  [SMALL_STATE(29)] = 260,
  [SMALL_STATE(30)] = 281,
  [SMALL_STATE(31)] = 302,
  [SMALL_STATE(32)] = 323,
  [SMALL_STATE(33)] = 344,
  [SMALL_STATE(34)] = 362,
  [SMALL_STATE(35)] = 380,
  [SMALL_STATE(36)] = 398,
  [SMALL_STATE(37)] = 416,
  [SMALL_STATE(38)] = 434,
  [SMALL_STATE(39)] = 444,
  [SMALL_STATE(40)] = 457,
  [SMALL_STATE(41)] = 470,
  [SMALL_STATE(42)] = 483,
  [SMALL_STATE(43)] = 496,
  [SMALL_STATE(44)] = 509,
  [SMALL_STATE(45)] = 522,
  [SMALL_STATE(46)] = 535,
  [SMALL_STATE(47)] = 548,
  [SMALL_STATE(48)] = 561,
  [SMALL_STATE(49)] = 574,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(2),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [43] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_array_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [66] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [69] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(40),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [133] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [139] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 2, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 2, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_array, 3, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_array, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 2, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dictionary, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dictionary, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [179] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [182] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [185] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_escape_sequence, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0),
  [205] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2, 0, 0), SHIFT_REPEAT(39),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0),
  [212] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat3, 2, 0, 0), SHIFT_REPEAT(41),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [223] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [225] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_structure_comment = 0,
  ts_external_token_literal_string = 1,
  ts_external_token_hexadecimal_string = 2,
  ts_external_token_base85_string = 3,
  ts_external_token_radix_number = 4,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_structure_comment] = sym_structure_comment,
  [ts_external_token_literal_string] = sym_literal_string,
  [ts_external_token_hexadecimal_string] = sym_hexadecimal_string,
  [ts_external_token_base85_string] = sym_base85_string,
  [ts_external_token_radix_number] = sym_radix_number,
};

static const bool ts_external_scanner_states[7][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_structure_comment] = true,
    [ts_external_token_literal_string] = true,
    [ts_external_token_hexadecimal_string] = true,
    [ts_external_token_base85_string] = true,
    [ts_external_token_radix_number] = true,
  },
  [2] = {
    [ts_external_token_structure_comment] = true,
    [ts_external_token_radix_number] = true,
  },
  [3] = {
    [ts_external_token_radix_number] = true,
  },
  [4] = {
    [ts_external_token_literal_string] = true,
  },
  [5] = {
    [ts_external_token_hexadecimal_string] = true,
  },
  [6] = {
    [ts_external_token_base85_string] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_postscript_external_scanner_create(void);
void tree_sitter_postscript_external_scanner_destroy(void *);
bool tree_sitter_postscript_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_postscript_external_scanner_serialize(void *, char *);
void tree_sitter_postscript_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_postscript(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_postscript_external_scanner_create,
      tree_sitter_postscript_external_scanner_destroy,
      tree_sitter_postscript_external_scanner_scan,
      tree_sitter_postscript_external_scanner_serialize,
      tree_sitter_postscript_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
